### ISSUE TITLE
Handshake status 502 Bad Gateway

### ISSUE THREAD

**Issue by gzuuus** [BrightonBTC/bija#18] opened 2022-12-28 22:16 UTC
I got this message when running bija
```
Bija is now running at http://localhost:5000
websocket connected
[_logging.py:66 -              warning() ] websocket connected
websocket connected
[_logging.py:66 -              warning() ] websocket connected
websocket connected
[_logging.py:66 -              warning() ] websocket connected
websocket connected
[_logging.py:66 -              warning() ] websocket connected
websocket connected
[_logging.py:66 -              warning() ] websocket connected
Handshake status 502 Bad Gateway - goodbye
[_logging.py:62 -                error() ] Handshake status 502 Bad Gateway - goodbye
Handshake status 502 Bad Gateway - goodbye
[_logging.py:62 -                error() ] Handshake status 502 Bad Gateway - goodbye
```

I tried changing the port, but nothing changed.
Even though the localhost address was still accessible and I could access the bija front panel.
The logs continued to give more clues:

```
[app.py:1741 -        log_exception() ] Exception on / [GET]
Traceback (most recent call last):
  File "sqlalchemy/engine/base.py", line 1900, in _execute_context
  File "sqlalchemy/engine/default.py", line 736, in do_execute
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "flask/app.py", line 2525, in wsgi_app
  File "flask/app.py", line 1822, in full_dispatch_request
  File "flask/app.py", line 1820, in full_dispatch_request
  File "flask/app.py", line 1796, in dispatch_request
  File "bija/routes.py", line 59, in decorated_function
  File "bija/routes.py", line 68, in index_page
  File "bija/db.py", line 389, in set_all_seen_in_feed
  File "sqlalchemy/orm/query.py", line 2901, in __iter__
  File "sqlalchemy/orm/query.py", line 2916, in _iter
  File "sqlalchemy/orm/session.py", line 1714, in execute
  File "sqlalchemy/engine/base.py", line 1705, in _execute_20
  File "sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
  File "sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
  File "sqlalchemy/engine/base.py", line 1943, in _execute_context
  File "sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
  File "sqlalchemy/util/compat.py", line 211, in raise_
  File "sqlalchemy/engine/base.py", line 1900, in _execute_context
  File "sqlalchemy/engine/default.py", line 736, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT note.id AS note_id, note.public_key AS note_public_key, note.content AS note_content, note.response_to AS note_response_to, note.thread_root AS note_thread_root, note.reshare AS note_reshare, note.created_at AS note_created_at, note.members AS note_members, note.media AS note_media, note.seen AS note_seen, note.liked AS note_liked, note.shared AS note_shared, note.raw AS note_raw, note.deleted AS note_deleted 
FROM note JOIN profile ON profile.public_key = note.public_key 
WHERE profile.following=1 OR profile.public_key='40b9c85fffeafc1cadf8c30a4e5c88660ff6e4971a0dc723d5ab674b5e61b451']
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[app.py:1741 -        log_exception() ] Exception on / [GET]
Traceback (most recent call last):
  File "sqlalchemy/engine/base.py", line 1900, in _execute_context
  File "sqlalchemy/engine/default.py", line 736, in do_execute
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "flask/app.py", line 2525, in wsgi_app
  File "flask/app.py", line 1822, in full_dispatch_request
  File "flask/app.py", line 1820, in full_dispatch_request
  File "flask/app.py", line 1796, in dispatch_request
  File "bija/routes.py", line 59, in decorated_function
  File "bija/routes.py", line 70, in index_page
  File "bija/notes.py", line 23, in __init__
  File "bija/notes.py", line 51, in build
  File "bija/notes.py", line 83, in build_thread
  File "bija/db.py", line 212, in get_note
  File "sqlalchemy/orm/query.py", line 2824, in first
  File "sqlalchemy/orm/query.py", line 2916, in _iter
  File "sqlalchemy/orm/session.py", line 1714, in execute
  File "sqlalchemy/engine/base.py", line 1705, in _execute_20
  File "sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
  File "sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
  File "sqlalchemy/engine/base.py", line 1943, in _execute_context
  File "sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
  File "sqlalchemy/util/compat.py", line 211, in raise_
  File "sqlalchemy/engine/base.py", line 1900, in _execute_context
  File "sqlalchemy/engine/default.py", line 736, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT note.id AS note_id, note.public_key AS note_public_key, note.content AS note_content, note.response_to AS note_response_to, note.thread_root AS note_thread_root, note.reshare AS note_reshare, note.created_at AS note_created_at, note.members AS note_members, note.media AS note_media, reaction_tally.likes AS reaction_tally_likes, reaction_tally.replies AS reaction_tally_replies, reaction_tally.shares AS reaction_tally_shares, note.liked AS note_liked, note.shared AS note_shared, note.deleted AS note_deleted, profile.name AS profile_name, profile.pic AS profile_pic, profile.nip05 AS profile_nip05, profile.nip05_validated AS profile_nip05_validated, profile.following AS profile_following 
FROM note LEFT OUTER JOIN reaction_tally ON reaction_tally.event_id = note.id JOIN profile ON profile.public_key = note.public_key 
WHERE note.id = ?
 LIMIT ? OFFSET ?]
[parameters: ('5c3471bd1fda302d309d107793774f39a20d000a627fb9c0126990175c52a6cb', 1, 0)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
bs4/__init__.py:404: MarkupResemblesLocatorWarning: The input looks more like a URL than markup. You may want to use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
[app.py:1741 -        log_exception() ] Exception on / [GET]
Traceback (most recent call last):
  File "sqlalchemy/engine/base.py", line 1900, in _execute_context
  File "sqlalchemy/engine/default.py", line 736, in do_execute
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "flask/app.py", line 2525, in wsgi_app
  File "flask/app.py", line 1822, in full_dispatch_request
  File "flask/app.py", line 1820, in full_dispatch_request
  File "flask/app.py", line 1796, in dispatch_request
  File "bija/routes.py", line 59, in decorated_function
  File "bija/routes.py", line 70, in index_page
  File "bija/notes.py", line 23, in __init__
  File "bija/notes.py", line 51, in build
  File "bija/notes.py", line 83, in build_thread
  File "bija/db.py", line 212, in get_note
  File "sqlalchemy/orm/query.py", line 2824, in first
  File "sqlalchemy/orm/query.py", line 2916, in _iter
  File "sqlalchemy/orm/session.py", line 1714, in execute
  File "sqlalchemy/engine/base.py", line 1705, in _execute_20
  File "sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
  File "sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
  File "sqlalchemy/engine/base.py", line 1943, in _execute_context
  File "sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
  File "sqlalchemy/util/compat.py", line 211, in raise_
  File "sqlalchemy/engine/base.py", line 1900, in _execute_context
  File "sqlalchemy/engine/default.py", line 736, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT note.id AS note_id, note.public_key AS note_public_key, note.content AS note_content, note.response_to AS note_response_to, note.thread_root AS note_thread_root, note.reshare AS note_reshare, note.created_at AS note_created_at, note.members AS note_members, note.media AS note_media, reaction_tally.likes AS reaction_tally_likes, reaction_tally.replies AS reaction_tally_replies, reaction_tally.shares AS reaction_tally_shares, note.liked AS note_liked, note.shared AS note_shared, note.deleted AS note_deleted, profile.name AS profile_name, profile.pic AS profile_pic, profile.nip05 AS profile_nip05, profile.nip05_validated AS profile_nip05_validated, profile.following AS profile_following 
FROM note LEFT OUTER JOIN reaction_tally ON reaction_tally.event_id = note.id JOIN profile ON profile.public_key = note.public_key 
WHERE note.id = ?
 LIMIT ? OFFSET ?]
[parameters: ('f02a888b758fa1e26a07e1a5d25d20a17580984ae10c955b5d6583f24265a7d5', 1, 0)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
Connection to remote host was lost. - goodbye
```

What do you think? I hope that can help as much as possible.

**Comment by BrightonBTC** [comment] 2022-12-29 09:58
Hi there, 

that first block of messages you received with the "Handshake status 502 Bad Gateway - goodbye" weren't an error in the app itself, they were just reporting on the status of the connection to relays, I can see how that would be unclear though.

Did you try opening http://localhost:5000 in your browser at that point? I suspect everything would've been running fine if you had, although it can take some time to sync with the network if you were loading an existing private key.

The subsequent errors are because the database is locked. This is probably caused by an error occurring during a write operation, that could either have been an error in the app itself, or if you force shut the app from the console after seeing the initial messages that could also be the issue (it's best to always log out using the logout link in the UI so that there's a clean shutdown). 

Like I said, on the initial loading of Bija it can take some time to sync with the network (assuming you were loading an existing account with various follows, messages, notifications, etc.) Those database errors could appear if you were trying to do other stuff in the app during the sync. Basically if the database was really busy writing all your data and you were trying to access it to load other pages etc.. When loading an existing account it's best to just let it do its thing for a few mins.

The database file will be in the location where you ran bija from and is named _bija.sqlite_, if it's still locked there will also be a file named something like _bija.sqlite-journal_. If that is there then I'd just delete both files and start again, or if you only see the database file then I'd try to run it again before deleting.

Hope this helps. Do let me know how it goes.

**Closed** 2023-01-06 13:25 UTC
